// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Candidate is the predicate function for candidate builders.
type Candidate func(*sql.Selector)

// Segment is the predicate function for segment builders.
type Segment func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// WordAlignment is the predicate function for wordalignment builders.
type WordAlignment func(*sql.Selector)
