// Code generated by entc, DO NOT EDIT.

package wordalignment

import (
	"asr-demo-server/pkg/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Start applies equality check predicate on the "start" field. It's identical to StartEQ.
func Start(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStart), v))
	})
}

// Length applies equality check predicate on the "length" field. It's identical to LengthEQ.
func Length(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLength), v))
	})
}

// Word applies equality check predicate on the "word" field. It's identical to WordEQ.
func Word(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWord), v))
	})
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldToken), v))
	})
}

// Confidence applies equality check predicate on the "confidence" field. It's identical to ConfidenceEQ.
func Confidence(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldConfidence), v))
	})
}

// StartEQ applies the EQ predicate on the "start" field.
func StartEQ(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStart), v))
	})
}

// StartNEQ applies the NEQ predicate on the "start" field.
func StartNEQ(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStart), v))
	})
}

// StartIn applies the In predicate on the "start" field.
func StartIn(vs ...float64) predicate.WordAlignment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.WordAlignment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStart), v...))
	})
}

// StartNotIn applies the NotIn predicate on the "start" field.
func StartNotIn(vs ...float64) predicate.WordAlignment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.WordAlignment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStart), v...))
	})
}

// StartGT applies the GT predicate on the "start" field.
func StartGT(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStart), v))
	})
}

// StartGTE applies the GTE predicate on the "start" field.
func StartGTE(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStart), v))
	})
}

// StartLT applies the LT predicate on the "start" field.
func StartLT(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStart), v))
	})
}

// StartLTE applies the LTE predicate on the "start" field.
func StartLTE(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStart), v))
	})
}

// LengthEQ applies the EQ predicate on the "length" field.
func LengthEQ(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLength), v))
	})
}

// LengthNEQ applies the NEQ predicate on the "length" field.
func LengthNEQ(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLength), v))
	})
}

// LengthIn applies the In predicate on the "length" field.
func LengthIn(vs ...float64) predicate.WordAlignment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.WordAlignment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLength), v...))
	})
}

// LengthNotIn applies the NotIn predicate on the "length" field.
func LengthNotIn(vs ...float64) predicate.WordAlignment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.WordAlignment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLength), v...))
	})
}

// LengthGT applies the GT predicate on the "length" field.
func LengthGT(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLength), v))
	})
}

// LengthGTE applies the GTE predicate on the "length" field.
func LengthGTE(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLength), v))
	})
}

// LengthLT applies the LT predicate on the "length" field.
func LengthLT(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLength), v))
	})
}

// LengthLTE applies the LTE predicate on the "length" field.
func LengthLTE(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLength), v))
	})
}

// WordEQ applies the EQ predicate on the "word" field.
func WordEQ(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWord), v))
	})
}

// WordNEQ applies the NEQ predicate on the "word" field.
func WordNEQ(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldWord), v))
	})
}

// WordIn applies the In predicate on the "word" field.
func WordIn(vs ...string) predicate.WordAlignment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.WordAlignment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldWord), v...))
	})
}

// WordNotIn applies the NotIn predicate on the "word" field.
func WordNotIn(vs ...string) predicate.WordAlignment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.WordAlignment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldWord), v...))
	})
}

// WordGT applies the GT predicate on the "word" field.
func WordGT(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldWord), v))
	})
}

// WordGTE applies the GTE predicate on the "word" field.
func WordGTE(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldWord), v))
	})
}

// WordLT applies the LT predicate on the "word" field.
func WordLT(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldWord), v))
	})
}

// WordLTE applies the LTE predicate on the "word" field.
func WordLTE(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldWord), v))
	})
}

// WordContains applies the Contains predicate on the "word" field.
func WordContains(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldWord), v))
	})
}

// WordHasPrefix applies the HasPrefix predicate on the "word" field.
func WordHasPrefix(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldWord), v))
	})
}

// WordHasSuffix applies the HasSuffix predicate on the "word" field.
func WordHasSuffix(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldWord), v))
	})
}

// WordEqualFold applies the EqualFold predicate on the "word" field.
func WordEqualFold(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldWord), v))
	})
}

// WordContainsFold applies the ContainsFold predicate on the "word" field.
func WordContainsFold(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldWord), v))
	})
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldToken), v))
	})
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldToken), v))
	})
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.WordAlignment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.WordAlignment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldToken), v...))
	})
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.WordAlignment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.WordAlignment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldToken), v...))
	})
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldToken), v))
	})
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldToken), v))
	})
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldToken), v))
	})
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldToken), v))
	})
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldToken), v))
	})
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldToken), v))
	})
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldToken), v))
	})
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldToken), v))
	})
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldToken), v))
	})
}

// ConfidenceEQ applies the EQ predicate on the "confidence" field.
func ConfidenceEQ(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldConfidence), v))
	})
}

// ConfidenceNEQ applies the NEQ predicate on the "confidence" field.
func ConfidenceNEQ(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldConfidence), v))
	})
}

// ConfidenceIn applies the In predicate on the "confidence" field.
func ConfidenceIn(vs ...float64) predicate.WordAlignment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.WordAlignment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldConfidence), v...))
	})
}

// ConfidenceNotIn applies the NotIn predicate on the "confidence" field.
func ConfidenceNotIn(vs ...float64) predicate.WordAlignment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.WordAlignment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldConfidence), v...))
	})
}

// ConfidenceGT applies the GT predicate on the "confidence" field.
func ConfidenceGT(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldConfidence), v))
	})
}

// ConfidenceGTE applies the GTE predicate on the "confidence" field.
func ConfidenceGTE(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldConfidence), v))
	})
}

// ConfidenceLT applies the LT predicate on the "confidence" field.
func ConfidenceLT(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldConfidence), v))
	})
}

// ConfidenceLTE applies the LTE predicate on the "confidence" field.
func ConfidenceLTE(v float64) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldConfidence), v))
	})
}

// HasCandidates applies the HasEdge predicate on the "candidates" edge.
func HasCandidates() predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CandidatesTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CandidatesTable, CandidatesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCandidatesWith applies the HasEdge predicate on the "candidates" edge with a given conditions (other predicates).
func HasCandidatesWith(preds ...predicate.Candidate) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CandidatesInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CandidatesTable, CandidatesColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WordAlignment) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WordAlignment) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WordAlignment) predicate.WordAlignment {
	return predicate.WordAlignment(func(s *sql.Selector) {
		p(s.Not())
	})
}
