// Code generated by entc, DO NOT EDIT.

package ent

import (
	"asr-demo-recognize/pkg/ent/segment"
	"asr-demo-recognize/pkg/ent/wordalignment"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SegmentCreate is the builder for creating a Segment entity.
type SegmentCreate struct {
	config
	mutation *SegmentMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (sc *SegmentCreate) SetType(s segment.Type) *SegmentCreate {
	sc.mutation.SetType(s)
	return sc
}

// SetStart sets the "start" field.
func (sc *SegmentCreate) SetStart(f float64) *SegmentCreate {
	sc.mutation.SetStart(f)
	return sc
}

// SetLength sets the "length" field.
func (sc *SegmentCreate) SetLength(f float64) *SegmentCreate {
	sc.mutation.SetLength(f)
	return sc
}

// SetID sets the "id" field.
func (sc *SegmentCreate) SetID(s string) *SegmentCreate {
	sc.mutation.SetID(s)
	return sc
}

// AddWordAlignmentIDs adds the "wordAlignments" edge to the WordAlignment entity by IDs.
func (sc *SegmentCreate) AddWordAlignmentIDs(ids ...int) *SegmentCreate {
	sc.mutation.AddWordAlignmentIDs(ids...)
	return sc
}

// AddWordAlignments adds the "wordAlignments" edges to the WordAlignment entity.
func (sc *SegmentCreate) AddWordAlignments(w ...*WordAlignment) *SegmentCreate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return sc.AddWordAlignmentIDs(ids...)
}

// Mutation returns the SegmentMutation object of the builder.
func (sc *SegmentCreate) Mutation() *SegmentMutation {
	return sc.mutation
}

// Save creates the Segment in the database.
func (sc *SegmentCreate) Save(ctx context.Context) (*Segment, error) {
	var (
		err  error
		node *Segment
	)
	if len(sc.hooks) == 0 {
		if err = sc.check(); err != nil {
			return nil, err
		}
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SegmentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sc.check(); err != nil {
				return nil, err
			}
			sc.mutation = mutation
			if node, err = sc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			if sc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SegmentCreate) SaveX(ctx context.Context) *Segment {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SegmentCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SegmentCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SegmentCreate) check() error {
	if _, ok := sc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "type"`)}
	}
	if v, ok := sc.mutation.GetType(); ok {
		if err := segment.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "type": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Start(); !ok {
		return &ValidationError{Name: "start", err: errors.New(`ent: missing required field "start"`)}
	}
	if v, ok := sc.mutation.Start(); ok {
		if err := segment.StartValidator(v); err != nil {
			return &ValidationError{Name: "start", err: fmt.Errorf(`ent: validator failed for field "start": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Length(); !ok {
		return &ValidationError{Name: "length", err: errors.New(`ent: missing required field "length"`)}
	}
	if v, ok := sc.mutation.Length(); ok {
		if err := segment.LengthValidator(v); err != nil {
			return &ValidationError{Name: "length", err: fmt.Errorf(`ent: validator failed for field "length": %w`, err)}
		}
	}
	if v, ok := sc.mutation.ID(); ok {
		if err := segment.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "id": %w`, err)}
		}
	}
	return nil
}

func (sc *SegmentCreate) sqlSave(ctx context.Context) (*Segment, error) {
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = _spec.ID.Value.(string)
	}
	return _node, nil
}

func (sc *SegmentCreate) createSpec() (*Segment, *sqlgraph.CreateSpec) {
	var (
		_node = &Segment{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: segment.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: segment.FieldID,
			},
		}
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.GetType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: segment.FieldType,
		})
		_node.Type = value
	}
	if value, ok := sc.mutation.Start(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: segment.FieldStart,
		})
		_node.Start = value
	}
	if value, ok := sc.mutation.Length(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: segment.FieldLength,
		})
		_node.Length = value
	}
	if nodes := sc.mutation.WordAlignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   segment.WordAlignmentsTable,
			Columns: []string{segment.WordAlignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: wordalignment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SegmentCreateBulk is the builder for creating many Segment entities in bulk.
type SegmentCreateBulk struct {
	config
	builders []*SegmentCreate
}

// Save creates the Segment entities in the database.
func (scb *SegmentCreateBulk) Save(ctx context.Context) ([]*Segment, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Segment, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SegmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SegmentCreateBulk) SaveX(ctx context.Context) []*Segment {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SegmentCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SegmentCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
