// Code generated by entc, DO NOT EDIT.

package ent

import (
	"asr-demo-server/pkg/ent/candidate"
	"asr-demo-server/pkg/ent/predicate"
	"asr-demo-server/pkg/ent/wordalignment"
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WordAlignmentQuery is the builder for querying WordAlignment entities.
type WordAlignmentQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.WordAlignment
	// eager-loading edges.
	withCandidates *CandidateQuery
	withFKs        bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WordAlignmentQuery builder.
func (waq *WordAlignmentQuery) Where(ps ...predicate.WordAlignment) *WordAlignmentQuery {
	waq.predicates = append(waq.predicates, ps...)
	return waq
}

// Limit adds a limit step to the query.
func (waq *WordAlignmentQuery) Limit(limit int) *WordAlignmentQuery {
	waq.limit = &limit
	return waq
}

// Offset adds an offset step to the query.
func (waq *WordAlignmentQuery) Offset(offset int) *WordAlignmentQuery {
	waq.offset = &offset
	return waq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (waq *WordAlignmentQuery) Unique(unique bool) *WordAlignmentQuery {
	waq.unique = &unique
	return waq
}

// Order adds an order step to the query.
func (waq *WordAlignmentQuery) Order(o ...OrderFunc) *WordAlignmentQuery {
	waq.order = append(waq.order, o...)
	return waq
}

// QueryCandidates chains the current query on the "candidates" edge.
func (waq *WordAlignmentQuery) QueryCandidates() *CandidateQuery {
	query := &CandidateQuery{config: waq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := waq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := waq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wordalignment.Table, wordalignment.FieldID, selector),
			sqlgraph.To(candidate.Table, candidate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, wordalignment.CandidatesTable, wordalignment.CandidatesColumn),
		)
		fromU = sqlgraph.SetNeighbors(waq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WordAlignment entity from the query.
// Returns a *NotFoundError when no WordAlignment was found.
func (waq *WordAlignmentQuery) First(ctx context.Context) (*WordAlignment, error) {
	nodes, err := waq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{wordalignment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (waq *WordAlignmentQuery) FirstX(ctx context.Context) *WordAlignment {
	node, err := waq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WordAlignment ID from the query.
// Returns a *NotFoundError when no WordAlignment ID was found.
func (waq *WordAlignmentQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = waq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{wordalignment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (waq *WordAlignmentQuery) FirstIDX(ctx context.Context) int {
	id, err := waq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WordAlignment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one WordAlignment entity is not found.
// Returns a *NotFoundError when no WordAlignment entities are found.
func (waq *WordAlignmentQuery) Only(ctx context.Context) (*WordAlignment, error) {
	nodes, err := waq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{wordalignment.Label}
	default:
		return nil, &NotSingularError{wordalignment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (waq *WordAlignmentQuery) OnlyX(ctx context.Context) *WordAlignment {
	node, err := waq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WordAlignment ID in the query.
// Returns a *NotSingularError when exactly one WordAlignment ID is not found.
// Returns a *NotFoundError when no entities are found.
func (waq *WordAlignmentQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = waq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{wordalignment.Label}
	default:
		err = &NotSingularError{wordalignment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (waq *WordAlignmentQuery) OnlyIDX(ctx context.Context) int {
	id, err := waq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WordAlignments.
func (waq *WordAlignmentQuery) All(ctx context.Context) ([]*WordAlignment, error) {
	if err := waq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return waq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (waq *WordAlignmentQuery) AllX(ctx context.Context) []*WordAlignment {
	nodes, err := waq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WordAlignment IDs.
func (waq *WordAlignmentQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := waq.Select(wordalignment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (waq *WordAlignmentQuery) IDsX(ctx context.Context) []int {
	ids, err := waq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (waq *WordAlignmentQuery) Count(ctx context.Context) (int, error) {
	if err := waq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return waq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (waq *WordAlignmentQuery) CountX(ctx context.Context) int {
	count, err := waq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (waq *WordAlignmentQuery) Exist(ctx context.Context) (bool, error) {
	if err := waq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return waq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (waq *WordAlignmentQuery) ExistX(ctx context.Context) bool {
	exist, err := waq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WordAlignmentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (waq *WordAlignmentQuery) Clone() *WordAlignmentQuery {
	if waq == nil {
		return nil
	}
	return &WordAlignmentQuery{
		config:         waq.config,
		limit:          waq.limit,
		offset:         waq.offset,
		order:          append([]OrderFunc{}, waq.order...),
		predicates:     append([]predicate.WordAlignment{}, waq.predicates...),
		withCandidates: waq.withCandidates.Clone(),
		// clone intermediate query.
		sql:  waq.sql.Clone(),
		path: waq.path,
	}
}

// WithCandidates tells the query-builder to eager-load the nodes that are connected to
// the "candidates" edge. The optional arguments are used to configure the query builder of the edge.
func (waq *WordAlignmentQuery) WithCandidates(opts ...func(*CandidateQuery)) *WordAlignmentQuery {
	query := &CandidateQuery{config: waq.config}
	for _, opt := range opts {
		opt(query)
	}
	waq.withCandidates = query
	return waq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Start float64 `json:"start,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WordAlignment.Query().
//		GroupBy(wordalignment.FieldStart).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (waq *WordAlignmentQuery) GroupBy(field string, fields ...string) *WordAlignmentGroupBy {
	group := &WordAlignmentGroupBy{config: waq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := waq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return waq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Start float64 `json:"start,omitempty"`
//	}
//
//	client.WordAlignment.Query().
//		Select(wordalignment.FieldStart).
//		Scan(ctx, &v)
//
func (waq *WordAlignmentQuery) Select(fields ...string) *WordAlignmentSelect {
	waq.fields = append(waq.fields, fields...)
	return &WordAlignmentSelect{WordAlignmentQuery: waq}
}

func (waq *WordAlignmentQuery) prepareQuery(ctx context.Context) error {
	for _, f := range waq.fields {
		if !wordalignment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if waq.path != nil {
		prev, err := waq.path(ctx)
		if err != nil {
			return err
		}
		waq.sql = prev
	}
	return nil
}

func (waq *WordAlignmentQuery) sqlAll(ctx context.Context) ([]*WordAlignment, error) {
	var (
		nodes       = []*WordAlignment{}
		withFKs     = waq.withFKs
		_spec       = waq.querySpec()
		loadedTypes = [1]bool{
			waq.withCandidates != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, wordalignment.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &WordAlignment{config: waq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, waq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := waq.withCandidates; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*WordAlignment)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Candidates = []*Candidate{}
		}
		query.withFKs = true
		query.Where(predicate.Candidate(func(s *sql.Selector) {
			s.Where(sql.InValues(wordalignment.CandidatesColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.word_alignment_candidates
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "word_alignment_candidates" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "word_alignment_candidates" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Candidates = append(node.Edges.Candidates, n)
		}
	}

	return nodes, nil
}

func (waq *WordAlignmentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := waq.querySpec()
	return sqlgraph.CountNodes(ctx, waq.driver, _spec)
}

func (waq *WordAlignmentQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := waq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (waq *WordAlignmentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   wordalignment.Table,
			Columns: wordalignment.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: wordalignment.FieldID,
			},
		},
		From:   waq.sql,
		Unique: true,
	}
	if unique := waq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := waq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wordalignment.FieldID)
		for i := range fields {
			if fields[i] != wordalignment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := waq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := waq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := waq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := waq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (waq *WordAlignmentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(waq.driver.Dialect())
	t1 := builder.Table(wordalignment.Table)
	columns := waq.fields
	if len(columns) == 0 {
		columns = wordalignment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if waq.sql != nil {
		selector = waq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range waq.predicates {
		p(selector)
	}
	for _, p := range waq.order {
		p(selector)
	}
	if offset := waq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := waq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WordAlignmentGroupBy is the group-by builder for WordAlignment entities.
type WordAlignmentGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wagb *WordAlignmentGroupBy) Aggregate(fns ...AggregateFunc) *WordAlignmentGroupBy {
	wagb.fns = append(wagb.fns, fns...)
	return wagb
}

// Scan applies the group-by query and scans the result into the given value.
func (wagb *WordAlignmentGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := wagb.path(ctx)
	if err != nil {
		return err
	}
	wagb.sql = query
	return wagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (wagb *WordAlignmentGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := wagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (wagb *WordAlignmentGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(wagb.fields) > 1 {
		return nil, errors.New("ent: WordAlignmentGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := wagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (wagb *WordAlignmentGroupBy) StringsX(ctx context.Context) []string {
	v, err := wagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wagb *WordAlignmentGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = wagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wordalignment.Label}
	default:
		err = fmt.Errorf("ent: WordAlignmentGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (wagb *WordAlignmentGroupBy) StringX(ctx context.Context) string {
	v, err := wagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (wagb *WordAlignmentGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(wagb.fields) > 1 {
		return nil, errors.New("ent: WordAlignmentGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := wagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (wagb *WordAlignmentGroupBy) IntsX(ctx context.Context) []int {
	v, err := wagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wagb *WordAlignmentGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = wagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wordalignment.Label}
	default:
		err = fmt.Errorf("ent: WordAlignmentGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (wagb *WordAlignmentGroupBy) IntX(ctx context.Context) int {
	v, err := wagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (wagb *WordAlignmentGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(wagb.fields) > 1 {
		return nil, errors.New("ent: WordAlignmentGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := wagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (wagb *WordAlignmentGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := wagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wagb *WordAlignmentGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = wagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wordalignment.Label}
	default:
		err = fmt.Errorf("ent: WordAlignmentGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (wagb *WordAlignmentGroupBy) Float64X(ctx context.Context) float64 {
	v, err := wagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (wagb *WordAlignmentGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(wagb.fields) > 1 {
		return nil, errors.New("ent: WordAlignmentGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := wagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (wagb *WordAlignmentGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := wagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wagb *WordAlignmentGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = wagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wordalignment.Label}
	default:
		err = fmt.Errorf("ent: WordAlignmentGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (wagb *WordAlignmentGroupBy) BoolX(ctx context.Context) bool {
	v, err := wagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (wagb *WordAlignmentGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range wagb.fields {
		if !wordalignment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := wagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (wagb *WordAlignmentGroupBy) sqlQuery() *sql.Selector {
	selector := wagb.sql.Select()
	aggregation := make([]string, 0, len(wagb.fns))
	for _, fn := range wagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(wagb.fields)+len(wagb.fns))
		for _, f := range wagb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(wagb.fields...)...)
}

// WordAlignmentSelect is the builder for selecting fields of WordAlignment entities.
type WordAlignmentSelect struct {
	*WordAlignmentQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (was *WordAlignmentSelect) Scan(ctx context.Context, v interface{}) error {
	if err := was.prepareQuery(ctx); err != nil {
		return err
	}
	was.sql = was.WordAlignmentQuery.sqlQuery(ctx)
	return was.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (was *WordAlignmentSelect) ScanX(ctx context.Context, v interface{}) {
	if err := was.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (was *WordAlignmentSelect) Strings(ctx context.Context) ([]string, error) {
	if len(was.fields) > 1 {
		return nil, errors.New("ent: WordAlignmentSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := was.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (was *WordAlignmentSelect) StringsX(ctx context.Context) []string {
	v, err := was.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (was *WordAlignmentSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = was.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wordalignment.Label}
	default:
		err = fmt.Errorf("ent: WordAlignmentSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (was *WordAlignmentSelect) StringX(ctx context.Context) string {
	v, err := was.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (was *WordAlignmentSelect) Ints(ctx context.Context) ([]int, error) {
	if len(was.fields) > 1 {
		return nil, errors.New("ent: WordAlignmentSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := was.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (was *WordAlignmentSelect) IntsX(ctx context.Context) []int {
	v, err := was.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (was *WordAlignmentSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = was.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wordalignment.Label}
	default:
		err = fmt.Errorf("ent: WordAlignmentSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (was *WordAlignmentSelect) IntX(ctx context.Context) int {
	v, err := was.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (was *WordAlignmentSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(was.fields) > 1 {
		return nil, errors.New("ent: WordAlignmentSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := was.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (was *WordAlignmentSelect) Float64sX(ctx context.Context) []float64 {
	v, err := was.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (was *WordAlignmentSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = was.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wordalignment.Label}
	default:
		err = fmt.Errorf("ent: WordAlignmentSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (was *WordAlignmentSelect) Float64X(ctx context.Context) float64 {
	v, err := was.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (was *WordAlignmentSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(was.fields) > 1 {
		return nil, errors.New("ent: WordAlignmentSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := was.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (was *WordAlignmentSelect) BoolsX(ctx context.Context) []bool {
	v, err := was.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (was *WordAlignmentSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = was.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{wordalignment.Label}
	default:
		err = fmt.Errorf("ent: WordAlignmentSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (was *WordAlignmentSelect) BoolX(ctx context.Context) bool {
	v, err := was.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (was *WordAlignmentSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := was.sql.Query()
	if err := was.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
